- name: "SCORED | 2.1.1 | Ensure xinetd is not installed"
  dnf:
    name: xinetd
    state: absent
  when:
    - rhel8cis_rule_2_1_1
  tags:
    - rhel8_section2
    - level1
    - scored
    - rule_2.1.1

- name: "NOTSCORED | 2.2.1.1 | Ensure time synchronization is in use"
  dnf:
    name: chrony
    state: present
  tags:
    - rhel8_section2
    - level1
    - rule_2.2.1.1

- name: "SCORED | 2.2.1.2 | Ensure chrony is configured"
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  when:
    - rhel8cis_rule_2_2_1_2
  tags:
    - rhel8_section2
    - level1
    - rule_2.2.1.2

- name: "SCORED | 2.2.2 | Ensure X Window System is not installed"
  dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - "xorg-x11*"
  when:
    - not rhel8cis_xwindows_required
    - rhel8cis_rule_2_2_2
  tags:
    - rhel8_section2
    - level1
    - scored
    - xwindows
    - rule_2.2.2


- name: "SCORED | 2.2.3 | Ensure rsync service is not enabled "
  systemd:
    name: rsyncd
    state: stopped
    enabled: no
  when:
    - rhel8cis_rsyncd_server == false and 'rsyncd' in ansible_facts.packages
    - rhel8cis_rule_2_2_3
  tags:
    - rhel8_section2
    - level1
    - rule_2.2.3

- name: "SCORED | 2.2.4 | Ensure Avahi Server is not enabled"
  systemd:
    name: avahi-daemon
    state: stopped
    enabled: no
  when:
    - rhel8cis_avahi_server == false and 'avahi' in ansible_facts.packages
    - rhel8cis_rule_2_2_4
  tags:
    - rhel8_section2
    - level1
    - scored
    - avahi
    - services
    - rule_2.2.4

- name: "SCORED | 2.2.5 | Ensure SNMP Server is not enabled"
  systemd:
    name: snmpd
    state: stopped
    enabled: no
  when:
    - rhel8cis_snmp_server == false and 'snmpd' in ansible_facts.packages
    - rhel8cis_rule_2_2_5
  tags:
    - rhel8_section2
    - level1
    - rule_2.2.5

- name: "SCORED | 2.2.6 | Ensure HTTP Proxy Server is not enabled"
  systemd:
    name: squid
    state: stopped
    enabled: no
  when:
    - rhel8cis_squid_server == false and 'squid' in ansible_facts.packages
    - rhel8cis_rule_2_2_6
  tags:
    - rhel8_section2
    - level1
    - rule_2.2.6

- name: "SCORED | 2.2.7 | Ensure Samba is not enabled"
  systemd:
    name: smb
    state: stopped
    enabled: no
  when:
    - rhel8cis_smb_server == false and 'smb' in ansible_facts.packages
    - rhel8cis_rule_2_2_7
  tags:
    - rhel8_section2
    - level1
    - rule_2.2.7

- name: "SCORED | 2.2.8 | Ensure IMAP and POP3 server is not enabled"
  systemd:
    name: dovecot
    state: stopped
    enabled: no
  when:
    - rhel8cis_rule_2_2_10 and 'dovecot' in ansible_facts.packages
  tags:
    - rhel8_section2
    - level1
    - scored
    - rule_2.2.10

- name: "SCORED | 2.2.11 | Ensure DNS Server is not enabled"
  systemd:
    name: named
    state: stopped
    enabled: no
  when:
    - rhel8cis_named_server == false and 'named' in ansible_facts.packages
    - rhel8cis_rule_2_2_11
  tags:
    - rhel8_section2
    - level1
    - rule_2.2.11

- name: "SCORED | 2.2.12 | Ensure NFS is not enabled"
  systemd:
    name: nfs
    state: stopped
    enabled: no
  when:
    - rhel8cis_nfs_rpc_server == false and 'nfs' in ansible_facts.packages
    - rhel8cis_rule_2_2_12
  tags:
    - rhel8_section2
    - level1
    - scored
    - nfs
    - rpc
    - services
    - rule_2.2.12

- name: "SCORED | 2.2.13 | Ensure RPC is not enabled"
  systemd:
    name: rpcbind
    state: stopped
    enabled: no
  when:
    - rhel8cis_nfs_rpc_server == false and 'rpcbind' in ansible_facts.packages
    - rhel8cis_rule_2_2_13
  tags:
    - rhel8_section2
    - level1
    - scored
    - nfs
    - rpc
    - services
    - rule_2.2.13

- name: "SCORED | 2.2.14 | Ensure LDAP server is not enabled"
  service:
    name: slapd
    state: stopped
    enabled: no
  when:
    - rhel8cis_ldap_server == false and 'slapd' in ansible_facts.packages
    - rhel8cis_rule_2_2_14
  tags:
    - rhel8_section2
    - level1
    - scored
    - ldap
    - services
    - rule_2.2.14

- name: "SCORED | 2.2.15 | Ensure DHCP Server is not enabled"
  systemd:
    name: dhcpd
    state: stopped
    enabled: no
  when:
    - rhel8cis_dhcp_server == false and 'dhcpd' in ansible_facts.packages
    - rhel8cis_rule_2_2_14
  tags:
    - rhel8_section2
    - level1
    - scored
    - dhcp
    - services
    - rule_2.2.14

- name: "SCORED | 2.2.16 | Ensure CUPS is not enabled"
  systemd:
    name: cups
    state: stopped
    enabled: no
  when:
    - rhel8cis_cups_server == false and 'cups' in ansible_facts.packages
    - rhel8cis_rule_2_2_16
  tags:
    - rhel8_section2
    - level1
    - scored
    - cups
    - services
    - rule_2.2.16

- name: "SCORED | 2.2.17 | Ensure NIS Server is not enabled"
  systemd:
    name: ypserv
    state: stopped
    enabled: no
  when:
    - rhel8cis_nis_server == false and 'ypserv' in ansible_facts.packages
    - rhel8cis_rule_2_2_17
  tags:
    - rhel8_section2
    - level1
    - rule_2.2.17

- name: "SCORED | 2.2.18 | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^(#)?inet_interfaces"
    line: "inet_interfaces = loopback-only"
  when:
    - rhel8cis_is_mail_server == false and 'postfix' in ansible_facts.packages
    - rhel8cis_rule_2_2_18
  tags:
    - rhel8_section2
    - level1
    - rule_2.2.18

- name: "SCORED | 2.2.9 | Ensure FTP Server is not enabled"
  service:
    name: vsftpd
    state: stopped
    enabled: no
  when:
    - rhel8cis_vsftpd_server == false and 'vsftpd' in ansible_facts.packages
    - rhel8cis_rule_2_2_9
  tags:
    - rhel8_section2
    - level1
    - rule_2.2.9

- name: "SCORED | 2.3.1 | Ensure NIS Client is not installed"
  dnf:
    name: ypbind
    state: absent
  when:
    - rhel8cis_ypbind_required == false
    - rhel8cis_rule_2_3_1
  tags:
    - rhel8_section2
    - level1
    - rule_2.3.1

- name: "SCORED | 2.3.2 | Ensure telnet client is not installed"
  dnf:
    name: telnet
    state: absent
  when:
    - rhel8cis_telnet_required == false and 'telnet' in ansible_facts.packages
    - rhel8cis_rule_2_3_2
  tags:
    - rhel8_section2
    - level1
    - rule_2.3.2

- name: "SCORED | 2.3.3 | Ensure LDAP client is not installed"
  dnf:
    name: openldap-clients
    state: absent
  when:
    - rhel8cis_openldap_clients_required == false
    - rhel8cis_rule_2_3_3
  tags:
    - rhel8_section2
    - level1
    - rule_2.3.3
