- name: "SCORED | 4.1.1.1 | Ensure auditd is installed"
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "audit"
    - "audit-libs"
  when:
    - rhel8cis_rule_4_1_1_1
  tags:
    - level1
    - level2
    - rule_4.1.1.1
    - rhel8_section4

- name: "SCORED | 4.1.1.2 | Ensure auditd service is enabled"
  systemd:
    name: auditd
    state: started
    enabled: yes
  when:
    - rhel8cis_rule_4_1_1_2
  tags:
    - level2
    - auditd
    - rule_4.1.1.2
    - rhel8_section4

- name: "SCORED | 4.1.1.3 | Ensure auditing for processes that start prior to auditd is enabled"
  replace:
    dest: /etc/default/grub
    regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit=1)(?:")'
    replace: '\1"\2 audit=1"'
    follow: yes
  ignore_errors: yes
  notify: generate new grub config
  when:
    - rhel7cis_rule_4_1_1_3
  tags:
    - level2
    - auditd
    - rule_4.1.1.3
    - rhel8_section4

- name: "SCORED | 4.1.1.4 | Ensure auditing for processes that start prior to auditd is enabled"
  replace:
    dest: /etc/default/grub
    regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit_backlog_limit=8192)(?:")'
    replace: '\1"\2 audit_backlog_limit=8192"'
    follow: yes
  ignore_errors: yes
  notify: generate new grub config
  when:
    - rhel7cis_rule_4_1_1_3
  tags:
    - level2
    - auditd
    - rule_4.1.1.3
    - rhel8_section4

- name: "NOTSCORED | 4.1.2.1 | Ensure audit log storage size is configured"
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: "^max_log_file( |=)"
    line: "max_log_file = 10"
    state: present
  when:
    - rhel8cis_rule_4_1_2_1
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.2.1
    - rhel8_section4

- name: "SCORED | 4.1.2.2 | Ensure audit logs are not automatically deleted"
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: "^max_log_file_action"
    line: "max_log_file_action = {{ rhel8cis_auditd['max_log_file_action'] }}"
    state: present
  when:
    - rhel8cis_rule_4_1_2_2
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.2.2
    - rhel8_section4

- name: "SCORED | 4.1.2.3 | Ensure system is disabled when audit logs are full"
  block:
    - name: "SCORED | 4.1.2.3 | Ensure system is disabled when audit logs are full"
      lineinfile:
        dest: /etc/audit/auditd.conf
        regexp: "^admin_space_left_action"
        line: "admin_space_left_action = {{ rhel8cis_auditd['admin_space_left_action'] }}"
        state: present
      notify: restart auditd

    - name: "SCORED | 4.1.2.3 | Ensure email on non-admin audit space alert"
      lineinfile:
        dest: /etc/audit/auditd.conf
        regexp: "^space_left_action"
        line: "space_left_action = email"
        state: present
      notify: restart auditd
  when:
    - rhel8cis_rule_4_1_2_3
  tags:
    - level2
    - auditd
    - rule_4.1.2.3
    - rhel8_section4

- name: "SCORED | 4.1.3 | Ensure changes to system administration scope (sudoers) is collected"
  template:
    src: audit/rhel8cis_rule_4_1_3.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_3.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_4_1_3
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.3
    - rhel8_section4

- name: "SCORED | 4.1.4 | Ensure login and logout events are collected"
  template:
    src: audit/rhel8cis_rule_4_1_4.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_4.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_4_1_4
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.8
    - rhel8_section4

- name: "SCORED | 4.1.5 | Ensure session initiation information is collected"
  template:
    src: audit/rhel8cis_rule_4_1_5.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_5.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_4_1_5
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.5
    - rhel8_section4

- name: "SCORED | 4.1.6 | Ensure events that modify date and time information are collected"
  template:
    src: audit/rhel8cis_rule_4_1_4.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_6.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_4_1_6
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.6
    - rhel8_section4

- name: "SCORED | 4.1.7 | Ensure events that modify the system's Mandatory Access Controls are collected"
  template:
    src: audit/rhel8cis_rule_4_1_7.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_7.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_4_1_7
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.7
    - rhel8_section4

- name: "SCORED | 4.1.8 | Ensure events that modify the system's network environment are collected"
  template:
    src: audit/rhel8cis_rule_4_1_8.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_8.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_4_1_8
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.8
    - rhel8_section4

- name: "SCORED | 4.1.9 | Ensure discretionary access control permission modification events are collected"
  template:
    src: audit/rhel8cis_rule_4_1_9.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_9.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_4_1_9
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.9
    - rhel8_section4

- name: "SCORED | 4.1.10 | Ensure unsuccessful unauthorized file access attempts are collected"
  template:
    src: audit/rhel8cis_rule_4_1_10.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_10.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_4_1_10
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.10
    - rhel8_section4

- name: "SCORED | 4.1.11 | Ensure events that modify user/group information are collected"
  template:
    src: audit/rhel8cis_rule_4_1_11.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_11.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_4_1_11
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.11
    - rhel8_section4

- name: "SCORED | 4.1.12 | Ensure successful file system mounts are collected"
  template:
    src: audit/rhel8cis_rule_4_1_12.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_12.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_4_1_12
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.12
    - rhel8_section4

- name: "SCORED | 4.1.13 | Ensure use of privileged commands is collected"
  shell: for i in  $(df | grep '^/dev' | awk '{ print $NF }'); do find $i -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null; done
  register: priv_procs
  changed_when: no
  check_mode: no
  when:
    - rhel8cis_rule_4_1_13
  tags:
    - level2
    - auditd
    - rule_4.1.13
    - rhel8_section4

- name: "SCORED | 4.1.13 | Ensure use of privileged commands is collected"
  template:
    src: audit/rhel8cis_rule_4_1_13.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_13.rules
    owner: root
    group: root
    mode: 0600
  notify: restart auditd
  when:
    - rhel8cis_rule_4_1_13
  tags:
    - level2
    - auditd
    - rule_4.1.13
    - rhel8_section4

- name: "SCORED | 4.1.14 | Ensure file deletion events by users are collected"
  template:
    src: audit/rhel8cis_rule_4_1_14.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_14.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_4_1_14
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.14
    - rhel8_section4

- name: "SCORED | 4.1.15 | Ensure kernel module loading and unloading is collected"
  template:
    src: audit/rhel8cis_rule_4_1_15.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_15.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_4_1_15
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.15
    - rhel8_section4

- name: "SCORED | 4.1.16 | Ensure system administrator actions (sudolog) are collected"
  template:
    src: audit/rhel8cis_rule_4_1_16.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_16.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_4_1_16
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.16
    - rhel8_section4

- name: "SCORED | 4.1.17 | Ensure the audit configuration is immutable"
  template:
    src: audit/rhel8cis_rule_4_1_17.rules.j2
    dest: /etc/audit/rules.d/rhel8cis_rule_4_1_17.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_4_1_17
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.17
    - rhel8_section4


- name: "SCORED | 4.2.1.1 | Ensure rsyslog is installed"
  dnf:
    name: "{{ rhel8cis_syslog }}"
    state: present
  when:
    - rhel8cis_rule_4_2_1_1
  tags:
    - level1
    - level2
    - rule_4.2.1.1
    - rhel8_section4

- name: "SCORED | 4.2.1.2 | Ensure rsyslog Service is enabled"
  systemd:
    name: rsyslog
    state: started
    enabled: yes
  when:
    - rhel8cis_rule_4_2_1_2
  tags:
    - level1
    - level2
    - rule_4.2.1.2
    - rhel8_section4
    - notimplemented

- name: "SCORED | 4.2.1.3 | Ensure rsyslog default file permissions configured"
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$FileCreateMode'
    line: '$FileCreateMode 0640'
  when:
    - rhel8cis_rule_4_2_1_3
  tags:
    - level1
    - level2
    - rule_4.2.1.3
    - rhel8_section4

- name: "NOTSCORED | 4.2.1.4 | Ensure logging is configured"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_rule_4_2_1_4
  tags:
    - level1
    - level2
    - rule_4.2.1.4
    - rhel8_section4
    - notimplemented

- name: "SCORED | 4.2.1.5 | Ensure rsyslog is configured to send logs to a remote log host"
  lineinfile:
    dest: /etc/rsyslog.conf
    insertbefore: '^$FileCreateMode 0640'
    line: '*.* @{{ rhel8rsyslog_dest  }}'
  when:
    - rhel8cis_rule_4_2_1_5
  tags:
    - level1
    - level2
    - rule_4.2.1.5
    - rhel8_section4
  ignore_errors: yes

- name: "NOTSCORED | 4.2.1.6 | Ensure remote rsyslog messages are only accepted on designated log hosts"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_rule_4_2_1_6
  tags:
    - level1
    - level2
    - rule_4.2.1.6
    - rhel8_section4
    - notimplemented

- name: "SCORED | 4.2.2.1 | Ensure journald is configured to send logs to rsyslog"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "^ForwardToSyslog"
    line: "ForwardToSyslog=yes"
    state: present
  when:
    - rhel8cis_rule_4_2_2_1
  tags:
    - level1
    - rule_4.2.2.1
    - rhel8_section4

- name: "SCORED | 4.2.2.2 | Ensure journald is configured to compress large log files"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "^Compress"
    line: "Compress=yes"
    state: present
  when:
    - rhel8cis_rule_4_2_2_2
  tags:
    - level1
    - rule_4.2.2.2
    - rhel8_section4

- name: "SCORED | 4.2.2.3 | Ensure journald is configured to write logfiles to persistent disk"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "^Storage"
    line: "Storage=persistent"
    state: present
  when:
    - rhel8cis_rule_4_2_2_3
  tags:
    - level1
    - rule_4.2.2.3
    - rhel8_section4

- name: "SCORED | 4.2.3 | Ensure permissions on all logfiles are configured"
  command: find /var/log -type f -exec chmod g-wx,o-rwx {} +
  changed_when: no
  failed_when: no
  when:
    - rhel8cis_rule_4_2_3
  tags:
    - level1
    - level2
    - rule_4.2.3
    - rhel8_section4

- name: "NOTSCORED | 4.3 | Ensure logrotate is configured"
  block:
    - name: "NOTSCORED | 4.3 | Ensure logrotate is configured"
      find:
        paths: /etc/logrotate.d/
      register: log_rotates

    - name: "NOTSCORED | 4.3 | Ensure logrotate is configured"
      replace:
        path: "{{ item.path }}"
        regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
        replace: "\\1{{ rhel8cis_logrotate }}"
      with_items:
        - "{{ log_rotates.files }}"
        - { path: "/etc/logrotate.conf" }
  tags:
    - level1
    - level2
    - rule_4.3
    - rhel8_section4
